### ISSUE TITLE
Gérer la recherche vide

### ISSUE THREAD

**Issue by JTE2** [tuarrep/janari#9]
Quand on soumet au formulaire un champ vide, on a une erreur indiquant que le code null n'existe pas. Il serait intéressant de gérer le null différemment que comme tous les autres produits introuvables.

**Comment by tuarrep** [comment]
Effectivement :+1: 
Idem quand le scan n'aboutit pas.

**Comment by JTE2** [comment]
Oui, bien vu.

**Comment by tuarrep** [comment]
Corrigé en V0.3.0 disponible cet après-midi
